export const API_ENDPOINTS = {
  AUTH: {
    LOGIN: "/auth/login",
    LOGOUT: "/auth/logout",
    ME: "/auth/me",
    FORGOT_PASSWORD: "/auth/forgot-password",
    RESET_PASSWORD: "/auth/reset-password",
  },

  USERS: {
    GET_ALL: "/users",
    GET_BY_ID: (id) => `/users/${id}`,
    GET_BY_EMAIL: "/users/by-email",
  },

  SALONS: {
    GET_ALL: "/businesses",
    GET_PENDING: "/businesses/pending",
    GET_VERIFIED: "/businesses/verified",
    GET_BY_ID: (id) => `/businesses/${id}`,
    GET_MY_BUSINESS: "/businesses/my-business",
    UPDATE_MY_BUSINESS: "/businesses/my-business",
    UPLOAD_BANNER: "/businesses/banner",
    UPLOAD_IMAGES: "/businesses/images",
    DELETE_IMAGE: "/businesses/images",
    VERIFY: (id) => `/businesses/${id}/verify`,
    GET_QR_CODE: (id) => `/businesses/${id}/qr-code`,
    GET_VERIFICATION_DOCUMENTS: (id) => `/businesses/verification/${id}/documents`,
    REVIEW_DOCUMENT: (documentId) => `/businesses/verification/documents/${documentId}/review`,
    GET_VERIFICATION_MESSAGES: (id) => `/businesses/verification/${id}/messages`,
    SEND_VERIFICATION_MESSAGE: (id) => `/businesses/verification/${id}/messages`,
  },

  CATEGORIES: {
    BASE: "/categories",
  },

  SERVICES: {
    BASE: "/services",
    GET_BY_BUSINESS: (businessId) => `/services/business/${businessId}`,
    UPDATE_BY_ID: (id) => `/services/${id}`,
    DELETE_BY_ID: (id) => `/services/${id}`,
  },

  STAFF: {
    BASE: "/staff",
    GET_BY_BUSINESS: (businessId) => `/staff/business/${businessId}`,
    GET_BY_SERVICE: (serviceId) => `/staff/service/${serviceId}`,
    GET_BY_ID: (id) => `/staff/${id}`,
    GET_BY_USER_ID: (userId) => `/staff/user/${userId}`,
    UPDATE_BY_ID: (id) => `/staff/${id}`,
    DELETE_BY_ID: (id) => `/staff/${id}`,
    ASSIGN_SERVICES: (id) => `/staff/${id}/services`,
    REMOVE_SERVICES: (id) => `/staff/${id}/services`,
    GENERATE_SLOTS: (id) => `/slots/staff/${id}/generate`,
    GET_SLOTS: (id) => `/slots/staff/${id}`,
    GET_SALARY: (id) => `/staff/${id}/salary`,
    GET_BUSINESS_SALARIES: (businessId) => `/staff/salary/business/${businessId}`,
    MY_SALARY: "/staff/my/salary",
  },
  REVIEWS: {
    GET_BY_BUSINESS: (businessId) => `/reviews/business/${businessId}`,
    GET_BY_STAFF: (staffId) => `/reviews/staff/${staffId}`,
    UPDATE_BY_ID: (id) => `/reviews/${id}`,
    DELETE_BY_ID: (id) => `/reviews/${id}`,
  },
  HOLIDAYS: {
    GET_BY_BUSINESS: (businessId) => `/business-holidays/business/${businessId}`,
    ADD: (businessId) => `/business-holidays/business/${businessId}`,
    UPDATE_BY_ID: (id) => `/business-holidays/${id}`,
    DELETE_BY_ID: (id) => `/business-holidays/${id}`,
  },
  BOOKINGS: {
    GET_BY_BUSINESS: (businessId) => `/bookings/business/${businessId}`,
    ACCEPT: (bookingId, staffId) => `/bookings/${bookingId}/accept?staffId=${staffId}`,
    REJECT: (bookingId) => `/bookings/${bookingId}/reject`,
    RESCHEDULE: (bookingId) => `/bookings/${bookingId}/reschedule`,
    UPDATE_STATUS: (bookingId, status) => `/bookings/staff/${bookingId}/status?status=${status}`,
    MY: "/bookings/my",
  },
  TIMINGS: {
    GET_BY_BUSINESS: (businessId) => `/business-timings/business/${businessId}`,
    UPDATE_BY_BUSINESS: (businessId) => `/business-timings/business/${businessId}`,
  },
  PAYMENTS: {
    GET_BOOKING_DETAILS: (bookingNumber) => `/payments/booking/${bookingNumber}`,
    PROCESS: "/payments/process",
    GET_BILL: (bookingNumber) => `/payments/bill/${bookingNumber}`,
  },
  SUPER_ADMIN: {
    DASHBOARD_STATS: "/superadmin/dashboard/stats",
    REVENUE_DAILY: "/superadmin/dashboard/revenue/daily",
    REVENUE_WEEKLY: "/superadmin/dashboard/revenue/weekly",
    REVENUE_MONTHLY: "/superadmin/dashboard/revenue/monthly",
    REVENUE_YEARLY: "/superadmin/dashboard/revenue/yearly",
    VISITS: "/superadmin/dashboard/visits",
    TOP_BUSINESSES: "/superadmin/dashboard/top/businesses",
    REVENUE_BY_CITY: "/superadmin/dashboard/revenue/by-city",
    REVENUE_BY_STATE: "/superadmin/dashboard/revenue/by-state",
    TOP_SALONS: "/superadmin/dashboard/top/salons",
    REVENUE_SUMMARY: "/superadmin/dashboard/revenue/summary",
  },
  DASHBOARD: {
    FULL: "/dashboard",
    REVENUE: "/dashboard/revenue",
    BOOKINGS: "/dashboard/bookings",
    TOP_SERVICES: "/dashboard/top-services",
    STAFF_PERFORMANCE: "/dashboard/staff-performance",
    CUSTOMER_INSIGHTS: "/dashboard/customer-insights",
    BUSINESS_HEALTH: "/dashboard/business-health",
  },
};